<div class="menuLocked" id="menu">
<div id='width'>
<div style='float:left;'>
<img src="/ink/icns/logo.png" height="22px" />
Ink Stock Manager 
<a href='/ink/ink.php' target='_parent'>Stock</a> 
<a href='/ink/printers/'>Printers</a> 
<a href='/ink/audit'>Audit</a> 
<a href='/ink/stockcheck/' target='_new'>Stock Check</a> 
<a href="javascript:ShowHide('ReportsMenu');">Reports</a> 
<a href="http://bespin/pcounter/home.php" target="_new">PCounter Logs</a>
</div>
<a href='/ink/manageusers/' target='_self'>Manage users</a> 
<a href='/ink/auth/auth.php?action=logout'>logout</a>
<div id="ReportsMenu" class="reports"  style="display:none;">
<a href="javascript:popup('/ink/reports/ink_usage/rules.php')">Ink Usage</a> 
<a href="javascript:popup('/ink/reports/printer_usage/rules.php')">Printer Usage</a> 
<a href="javascript:popup('/ink/reports/department_usage/rules.php')">Department Usage</a>
<a href="javascript:popup('/ink/stockwarning')" >Stock Warnings</a>
<a href="javascript:popup('/ink/reports/eod/rules.php')" >EOD Stock Report</a>
</div>
</div>
</div>
